/**
 * Settings Module
 * Comprehensive settings with real-time branding, profile management,
 * business configuration, receipt/invoice customization, notifications, and system preferences.
 */
(function () {
    'use strict';

    window.PharmaFlow = window.PharmaFlow || {};

    let unsubBusiness = null;

    const DEFAULT_SETTINGS = {
        name: 'PharmaFlow',
        tagline: 'Pharmacy Management System',
        address: '',
        phone: '',
        email: '',
        licenseNumber: '',
        logoIcon: 'fas fa-capsules',
        companyLogoUrl: '',
        receiptFooter: 'Thank you for your purchase!',
        invoiceFooter: 'Thank you for your business!',
        invoiceGenerated: 'This invoice was generated by {name} {tagline}',
        currency: 'KSH',
        locale: 'en-KE',
        notifyLowStock: true,
        notifyExpiry: true,
        notifyNewOrders: true,
        lowStockThreshold: 10,
        expiryWarningDays: 30,
        dateFormat: 'DD/MM/YYYY',
        timezone: 'Africa/Nairobi',
        emailJsServiceId: '',
        emailJsTemplateId: '',
        emailJsPublicKey: '',
        whatsappCallMeBotPhone: '',
        whatsappCallMeBotApiKey: ''
    };

    const ICON_OPTIONS = [
        { value: 'fas fa-capsules', label: 'Capsules' },
        { value: 'fas fa-pills', label: 'Pills' },
        { value: 'fas fa-prescription-bottle-medical', label: 'Prescription Bottle' },
        { value: 'fas fa-mortar-pestle', label: 'Mortar & Pestle' },
        { value: 'fas fa-hospital', label: 'Hospital' },
        { value: 'fas fa-clinic-medical', label: 'Clinic' },
        { value: 'fas fa-stethoscope', label: 'Stethoscope' },
        { value: 'fas fa-heartbeat', label: 'Heartbeat' },
        { value: 'fas fa-medkit', label: 'Medkit' },
        { value: 'fas fa-store', label: 'Store' },
        { value: 'fas fa-building', label: 'Building' },
        { value: 'fas fa-briefcase-medical', label: 'Medical Briefcase' }
    ];

    const CURRENCIES = [
        { value: 'KSH', label: 'KSH - Kenyan Shilling' },
        { value: 'USD', label: 'USD - US Dollar' },
        { value: 'EUR', label: 'EUR - Euro' },
        { value: 'GBP', label: 'GBP - British Pound' },
        { value: 'TZS', label: 'TZS - Tanzanian Shilling' },
        { value: 'UGX', label: 'UGX - Uganda Shilling' },
        { value: 'NGN', label: 'NGN - Nigerian Naira' },
        { value: 'ZAR', label: 'ZAR - South African Rand' }
    ];

    const LOCALES = [
        { value: 'en-KE', label: 'English (Kenya)' },
        { value: 'en-US', label: 'English (US)' },
        { value: 'en-GB', label: 'English (UK)' },
        { value: 'en-TZ', label: 'English (Tanzania)' },
        { value: 'en-UG', label: 'English (Uganda)' },
        { value: 'en-NG', label: 'English (Nigeria)' },
        { value: 'en-ZA', label: 'English (South Africa)' },
        { value: 'sw-KE', label: 'Swahili (Kenya)' }
    ];

    const DATE_FORMATS = [
        { value: 'DD/MM/YYYY', label: 'DD/MM/YYYY (31/12/2026)' },
        { value: 'MM/DD/YYYY', label: 'MM/DD/YYYY (12/31/2026)' },
        { value: 'YYYY-MM-DD', label: 'YYYY-MM-DD (2026-12-31)' }
    ];

    const TIMEZONES = [
        { value: 'Africa/Nairobi', label: 'East Africa Time (UTC+3)' },
        { value: 'Africa/Lagos', label: 'West Africa Time (UTC+1)' },
        { value: 'Africa/Johannesburg', label: 'South Africa Time (UTC+2)' },
        { value: 'Africa/Dar_es_Salaam', label: 'East Africa Time - TZ (UTC+3)' },
        { value: 'UTC', label: 'UTC' }
    ];


    const Settings = {
        business: { ...DEFAULT_SETTINGS },
        _initialized: false,

        // ─── INITIALIZATION ──────────────────────────────

        init: function () {
            if (this._initialized) return;
            this._initialized = true;
            this.listenBusinessSettings();
        },

        listenBusinessSettings: function () {
            const businessId = PharmaFlow.Auth && PharmaFlow.Auth.getBusinessId ? PharmaFlow.Auth.getBusinessId() : null;
            if (!businessId) return;

            if (unsubBusiness) unsubBusiness();

            unsubBusiness = window.db.collection('businesses').doc(businessId)
                .onSnapshot(function (doc) {
                    if (doc.exists) {
                        var d = doc.data();
                        Settings.business = {
                            name: d.name || DEFAULT_SETTINGS.name,
                            tagline: d.tagline || DEFAULT_SETTINGS.tagline,
                            address: d.address || '',
                            phone: d.phone || '',
                            email: d.email || '',
                            licenseNumber: d.licenseNumber || '',
                            logoIcon: d.logoIcon || DEFAULT_SETTINGS.logoIcon,
                            companyLogoUrl: d.companyLogoUrl || '',
                            receiptFooter: d.receiptFooter || DEFAULT_SETTINGS.receiptFooter,
                            invoiceFooter: d.invoiceFooter || DEFAULT_SETTINGS.invoiceFooter,
                            invoiceGenerated: d.invoiceGenerated || DEFAULT_SETTINGS.invoiceGenerated,
                            currency: d.currency || DEFAULT_SETTINGS.currency,
                            locale: d.locale || DEFAULT_SETTINGS.locale,
                            notifyLowStock: d.notifyLowStock !== false,
                            notifyExpiry: d.notifyExpiry !== false,
                            notifyNewOrders: d.notifyNewOrders !== false,
                            lowStockThreshold: d.lowStockThreshold || 10,
                            expiryWarningDays: d.expiryWarningDays || 30,
                            dateFormat: d.dateFormat || DEFAULT_SETTINGS.dateFormat,
                            timezone: d.timezone || DEFAULT_SETTINGS.timezone,
                            emailJsServiceId: d.emailJsServiceId || '',
                            emailJsTemplateId: d.emailJsTemplateId || '',
                            emailJsPublicKey: d.emailJsPublicKey || '',
                            whatsappCallMeBotPhone: d.whatsappCallMeBotPhone || '',
                            whatsappCallMeBotApiKey: d.whatsappCallMeBotApiKey || ''
                        };
                        Settings.applyBranding();
                        Settings.persistBrandToLocal();
                    }
                });
        },

        applyBranding: function () {
            document.title = this.business.name + ' - ' + this.business.tagline;

            var logoText = document.querySelector('.logo-text');
            if (logoText) logoText.textContent = this.business.name;

            var logoIcon = document.querySelector('.sidebar-logo > i');
            if (logoIcon) logoIcon.className = this.business.logoIcon;

            var topbarTitle = document.querySelector('.topbar-title');
            if (topbarTitle) topbarTitle.textContent = this.business.name;
        },

        persistBrandToLocal: function () {
            try {
                localStorage.setItem('pf_brand_name', this.business.name);
                localStorage.setItem('pf_brand_tagline', this.business.tagline);
                localStorage.setItem('pf_brand_icon', this.business.logoIcon);
            } catch (e) { /* ignore */ }
        },

        // ─── PUBLIC GETTERS (used by POS, Wholesale, etc.) ──

        getBusinessName: function () { return this.business.name; },
        getTagline: function () { return this.business.tagline; },
        getReceiptFooter: function () { return this.business.receiptFooter; },
        getInvoiceFooter: function () { return this.business.invoiceFooter; },
        getInvoiceGenerated: function () {
            return (this.business.invoiceGenerated || '')
                .replace('{name}', this.business.name)
                .replace('{tagline}', this.business.tagline);
        },
        getBusinessAddress: function () { return this.business.address; },
        getBusinessPhone: function () { return this.business.phone; },
        getBusinessEmail: function () { return this.business.email; },
        getLogoIcon: function () { return this.business.logoIcon; },
        getCompanyLogoUrl: function () { return this.business.companyLogoUrl; },
        getCurrency: function () { return this.business.currency; },
        getLocale: function () { return this.business.locale; },
        getMessagingIntegrations: function () {
            return {
                provider: this.business.messagingProvider || 'mixed',
                africaTalkingUsername: this.business.africaTalkingUsername || '',
                africaTalkingApiKey: this.business.africaTalkingApiKey || '',
                africaTalkingSenderId: this.business.africaTalkingSenderId || '',
                emailJsServiceId: this.business.emailJsServiceId || '',
                emailJsTemplateId: this.business.emailJsTemplateId || '',
                emailJsPublicKey: this.business.emailJsPublicKey || '',
                whatsappCallMeBotPhone: this.business.whatsappCallMeBotPhone || '',
                whatsappCallMeBotApiKey: this.business.whatsappCallMeBotApiKey || ''
            };
        },

        // ─── HELPERS ─────────────────────────────────────

        _showToast: function (msg, type) {
            if (window.showToast) { window.showToast(msg, type); return; }
            if (PharmaFlow.alert) { PharmaFlow.alert(msg); return; }
        },

        _isAdmin: function () {
            var role = PharmaFlow.Auth && PharmaFlow.Auth.userProfile ? PharmaFlow.Auth.userProfile.role : null;
            return role === 'superadmin' || role === 'admin';
        },

        _escapeHtml: function (text) {
            var div = document.createElement('div');
            div.textContent = text || '';
            return div.innerHTML;
        },

        _getInitials: function (name) {
            if (!name) return '?';
            var parts = name.trim().split(/\s+/);
            return parts.length >= 2
                ? (parts[0][0] + parts[parts.length - 1][0]).toUpperCase()
                : parts[0][0].toUpperCase();
        },

        _bindBreadcrumb: function (container) {
            var link = container.querySelector('[data-nav="dashboard"]');
            if (link) {
                link.addEventListener('click', function (e) {
                    e.preventDefault();
                    PharmaFlow.Sidebar.setActive('dashboard', null);
                });
            }
        },


        // ═══════════════════════════════════════════════════
        //  TAB 1 — MY PROFILE
        // ═══════════════════════════════════════════════════

        renderProfile: function (container) {
            var user = (PharmaFlow.Auth && PharmaFlow.Auth.userProfile) || {};
            var self = this;
            var photoURL = user.photoURL || '';
            var avatarContent = photoURL
                ? '<img src="' + self._escapeHtml(photoURL) + '" alt="Profile" class="st-avatar-img">'
                : self._getInitials(user.displayName);

            container.innerHTML =
                '<div class="page-header">' +
                '  <div><h2>My Profile</h2>' +
                '    <div class="breadcrumb">' +
                '      <a href="#" data-nav="dashboard">Home</a><span>/</span>' +
                '      <span>Settings</span><span>/</span><span>My Profile</span>' +
                '    </div>' +
                '  </div>' +
                '</div>' +

                '<div class="st-profile-layout">' +

                '  <div class="card st-profile-card">' +
                '    <div class="st-avatar-section">' +
                '      <div class="st-avatar-large" id="st-avatar-display">' + avatarContent + '</div>' +
                '      <div class="st-photo-upload">' +
                '        <label for="st-photo-input" class="st-photo-btn"><i class="fas fa-camera"></i> Change Photo</label>' +
                '        <input type="file" id="st-photo-input" accept="image/png,image/jpeg,image/webp" style="display:none;">' +
                '        <div class="st-photo-status" id="st-photo-status"></div>' +
                (photoURL ? '        <button class="st-photo-remove" id="st-photo-remove"><i class="fas fa-trash-alt"></i> Remove</button>' : '') +
                '      </div>' +
                '      <h3 class="st-profile-name">' + self._escapeHtml(user.displayName || 'User') + '</h3>' +
                '      <span class="st-role-badge st-role-' + (user.role || 'staff') + '">' + (user.role || 'staff').toUpperCase() + '</span>' +
                '      <p class="st-profile-email">' + self._escapeHtml(user.email || '') + '</p>' +
                '    </div>' +
                '  </div>' +

                '  <div class="card st-form-card">' +
                '    <h3 class="st-section-title"><i class="fas fa-user-edit"></i> Personal Information</h3>' +
                '    <form id="st-profile-form" class="st-form">' +
                '      <div class="st-form-row">' +
                '        <div class="form-group">' +
                '          <label for="st-display-name">Display Name</label>' +
                '          <input type="text" id="st-display-name" value="' + self._escapeHtml(user.displayName || '') + '" required>' +
                '        </div>' +
                '        <div class="form-group">' +
                '          <label for="st-email">Email Address</label>' +
                '          <input type="email" id="st-email" value="' + self._escapeHtml(user.email || '') + '" disabled>' +
                '          <small class="st-help-text">Email cannot be changed</small>' +
                '        </div>' +
                '      </div>' +
                '      <div class="st-form-row">' +
                '        <div class="form-group">' +
                '          <label for="st-phone">Phone Number</label>' +
                '          <input type="tel" id="st-phone" value="' + self._escapeHtml(user.phone || '') + '" placeholder="e.g., +254 712 345 678">' +
                '        </div>' +
                '        <div class="form-group">' +
                '          <label for="st-role-display">Role</label>' +
                '          <input type="text" id="st-role-display" value="' + (user.role || 'staff').toUpperCase() + '" disabled>' +
                '          <small class="st-help-text">Contact admin to change role</small>' +
                '        </div>' +
                '      </div>' +
                '      <div class="st-form-actions">' +
                '        <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save Changes</button>' +
                '      </div>' +
                '    </form>' +

                '    <hr class="st-divider">' +

                '    <h3 class="st-section-title"><i class="fas fa-lock"></i> Change Password</h3>' +
                '    <form id="st-password-form" class="st-form">' +
                '      <div class="st-form-row">' +
                '        <div class="form-group">' +
                '          <label for="st-current-password">Current Password</label>' +
                '          <input type="password" id="st-current-password" required placeholder="Enter current password">' +
                '        </div>' +
                '        <div class="form-group"></div>' +
                '      </div>' +
                '      <div class="st-form-row">' +
                '        <div class="form-group">' +
                '          <label for="st-new-password">New Password</label>' +
                '          <input type="password" id="st-new-password" required placeholder="Enter new password" minlength="6">' +
                '        </div>' +
                '        <div class="form-group">' +
                '          <label for="st-confirm-password">Confirm New Password</label>' +
                '          <input type="password" id="st-confirm-password" required placeholder="Confirm new password" minlength="6">' +
                '        </div>' +
                '      </div>' +
                '      <div class="st-form-actions">' +
                '        <button type="submit" class="btn btn-primary"><i class="fas fa-key"></i> Update Password</button>' +
                '      </div>' +
                '    </form>' +
                '  </div>' +

                '</div>';

            self._bindBreadcrumb(container);
            self._bindProfileForm(container);
            self._bindPasswordForm(container);
            self._bindPhotoUpload(container);
        },

        _bindProfileForm: function (container) {
            var form = container.querySelector('#st-profile-form');
            if (!form) return;
            var self = this;

            form.addEventListener('submit', async function (e) {
                e.preventDefault();
                var btn = form.querySelector('button[type="submit"]');
                btn.disabled = true;
                btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Saving...';

                try {
                    var uid = PharmaFlow.Auth && PharmaFlow.Auth.currentUser ? PharmaFlow.Auth.currentUser.uid : null;
                    if (!uid) throw new Error('Not authenticated');

                    var displayName = document.getElementById('st-display-name').value.trim();
                    var phone = document.getElementById('st-phone').value.trim();
                    if (!displayName) throw new Error('Display name is required');

                    await window.db.collection('users').doc(uid).update({
                        displayName: displayName,
                        phone: phone,
                        updatedAt: new Date().toISOString()
                    });

                    if (PharmaFlow.Auth.currentUser.updateProfile) {
                        await PharmaFlow.Auth.currentUser.updateProfile({ displayName: displayName });
                    }

                    PharmaFlow.Auth.userProfile.displayName = displayName;
                    PharmaFlow.Auth.userProfile.phone = phone;

                    // Update topbar
                    var profileName = document.getElementById('profile-name');
                    if (profileName) profileName.textContent = displayName;
                    var dropdownName = document.getElementById('dropdown-user-name');
                    if (dropdownName) dropdownName.textContent = displayName;
                    var profileAvatar = document.getElementById('profile-avatar');
                    if (profileAvatar) profileAvatar.textContent = self._getInitials(displayName);

                    // Update card
                    var nameEl = container.querySelector('.st-profile-name');
                    if (nameEl) nameEl.textContent = displayName;
                    var avatarEl = container.querySelector('.st-avatar-large');
                    if (avatarEl) avatarEl.textContent = self._getInitials(displayName);

                    if (PharmaFlow.ActivityLog) {
                        PharmaFlow.ActivityLog.log({
                            title: 'Profile Updated',
                            description: 'User updated their profile: ' + displayName,
                            category: 'User',
                            status: 'COMPLETED'
                        });
                    }

                    self._showToast('Profile updated successfully', 'success');
                } catch (err) {
                    console.error('Profile update failed:', err);
                    self._showToast(err.message || 'Failed to update profile', 'error');
                } finally {
                    btn.disabled = false;
                    btn.innerHTML = '<i class="fas fa-save"></i> Save Changes';
                }
            });
        },

        _bindPasswordForm: function (container) {
            var form = container.querySelector('#st-password-form');
            if (!form) return;
            var self = this;

            form.addEventListener('submit', async function (e) {
                e.preventDefault();
                var btn = form.querySelector('button[type="submit"]');
                btn.disabled = true;
                btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Updating...';

                try {
                    var currentPassword = document.getElementById('st-current-password').value;
                    var newPassword = document.getElementById('st-new-password').value;
                    var confirmPassword = document.getElementById('st-confirm-password').value;

                    if (newPassword !== confirmPassword) throw new Error('New passwords do not match');
                    if (newPassword.length < 6) throw new Error('Password must be at least 6 characters');

                    var user = firebase.auth().currentUser;
                    var credential = firebase.auth.EmailAuthProvider.credential(user.email, currentPassword);

                    await user.reauthenticateWithCredential(credential);
                    await user.updatePassword(newPassword);

                    form.reset();

                    if (PharmaFlow.ActivityLog) {
                        PharmaFlow.ActivityLog.log({
                            title: 'Password Changed',
                            description: 'User changed their password',
                            category: 'Auth',
                            status: 'COMPLETED'
                        });
                    }

                    self._showToast('Password updated successfully', 'success');
                } catch (err) {
                    console.error('Password change failed:', err);
                    var msg = 'Failed to change password';
                    if (err.code === 'auth/wrong-password') msg = 'Current password is incorrect';
                    else if (err.code === 'auth/weak-password') msg = 'New password is too weak';
                    else if (err.code === 'auth/requires-recent-login') msg = 'Please sign out and sign in again before changing password';
                    else if (err.message) msg = err.message;
                    self._showToast(msg, 'error');
                } finally {
                    btn.disabled = false;
                    btn.innerHTML = '<i class="fas fa-key"></i> Update Password';
                }
            });
        },

        _bindPhotoUpload: function (container) {
            var self = this;
            var fileInput = document.getElementById('st-photo-input');
            var statusEl = document.getElementById('st-photo-status');
            var removeBtn = document.getElementById('st-photo-remove');

            if (fileInput) {
                fileInput.addEventListener('change', async function () {
                    var file = fileInput.files[0];
                    if (!file) return;

                    // Validate file type
                    if (!file.type.match(/^image\/(png|jpeg|webp)$/)) {
                        self._showToast('Please select a PNG, JPEG, or WebP image', 'error');
                        fileInput.value = '';
                        return;
                    }
                    // Validate file size (2MB)
                    if (file.size > 2 * 1024 * 1024) {
                        self._showToast('Image must be less than 2MB', 'error');
                        fileInput.value = '';
                        return;
                    }

                    var uid = PharmaFlow.Auth && PharmaFlow.Auth.currentUser ? PharmaFlow.Auth.currentUser.uid : null;
                    if (!uid) { self._showToast('Not authenticated', 'error'); return; }

                    if (statusEl) statusEl.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Uploading...';

                    try {
                        var ext = file.name.split('.').pop().toLowerCase();
                        var ref = window.storage.ref('users/' + uid + '/profile_photo/avatar.' + ext);
                        var snapshot = await ref.put(file);
                        var downloadURL = await snapshot.ref.getDownloadURL();

                        // Save URL to Firestore user doc
                        await window.db.collection('users').doc(uid).update({
                            photoURL: downloadURL,
                            updatedAt: new Date().toISOString()
                        });

                        // Update local profile
                        PharmaFlow.Auth.userProfile.photoURL = downloadURL;

                        // Update avatar display
                        var avatarEl = document.getElementById('st-avatar-display');
                        if (avatarEl) avatarEl.innerHTML = '<img src="' + self._escapeHtml(downloadURL) + '" alt="Profile" class="st-avatar-img">';

                        // Update topbar avatar
                        var topAvatar = document.getElementById('profile-avatar');
                        if (topAvatar) topAvatar.innerHTML = '<img src="' + self._escapeHtml(downloadURL) + '" alt="Profile" class="st-avatar-img" style="width:100%;height:100%;border-radius:50%;object-fit:cover;">';

                        if (statusEl) statusEl.innerHTML = '<i class="fas fa-check" style="color:#16a34a;"></i> Uploaded!';
                        setTimeout(function () { if (statusEl) statusEl.innerHTML = ''; }, 3000);

                        // Add remove button if not present
                        if (!document.getElementById('st-photo-remove')) {
                            var uploadDiv = container.querySelector('.st-photo-upload');
                            if (uploadDiv) {
                                var btn = document.createElement('button');
                                btn.className = 'st-photo-remove';
                                btn.id = 'st-photo-remove';
                                btn.innerHTML = '<i class="fas fa-trash-alt"></i> Remove';
                                uploadDiv.appendChild(btn);
                                btn.addEventListener('click', function () { self._removePhoto(container); });
                            }
                        }

                        self._showToast('Profile photo updated', 'success');
                    } catch (err) {
                        console.error('Photo upload failed:', err);
                        if (statusEl) statusEl.innerHTML = '';
                        self._showToast('Failed to upload photo: ' + (err.message || 'Unknown error'), 'error');
                    }

                    fileInput.value = '';
                });
            }

            if (removeBtn) {
                removeBtn.addEventListener('click', function () { self._removePhoto(container); });
            }
        },

        _removePhoto: async function (container) {
            var self = this;
            var uid = PharmaFlow.Auth && PharmaFlow.Auth.currentUser ? PharmaFlow.Auth.currentUser.uid : null;
            if (!uid) return;

            try {
                // Remove from Firestore
                await window.db.collection('users').doc(uid).update({
                    photoURL: firebase.firestore.FieldValue.delete(),
                    updatedAt: new Date().toISOString()
                });

                // Try to delete from storage (ignore errors if file doesn't exist)
                try {
                    var extensions = ['png', 'jpeg', 'jpg', 'webp'];
                    for (var i = 0; i < extensions.length; i++) {
                        try {
                            await window.storage.ref('users/' + uid + '/profile_photo/avatar.' + extensions[i]).delete();
                        } catch (e) { /* file may not exist with this extension */ }
                    }
                } catch (e) { /* ignore storage errors */ }

                // Update local profile
                delete PharmaFlow.Auth.userProfile.photoURL;

                // Revert to initials
                var displayName = PharmaFlow.Auth.userProfile.displayName || 'User';
                var avatarEl = document.getElementById('st-avatar-display');
                if (avatarEl) avatarEl.innerHTML = self._getInitials(displayName);

                // Update topbar avatar
                var topAvatar = document.getElementById('profile-avatar');
                if (topAvatar) {
                    var initials = displayName.split(' ').map(function (n) { return n[0]; }).join('').substring(0, 2).toUpperCase();
                    topAvatar.innerHTML = '<span>' + initials + '</span>';
                }

                // Remove the remove button
                var removeBtn = document.getElementById('st-photo-remove');
                if (removeBtn) removeBtn.remove();

                self._showToast('Profile photo removed', 'success');
            } catch (err) {
                console.error('Remove photo failed:', err);
                self._showToast('Failed to remove photo', 'error');
            }
        },


        // ═══════════════════════════════════════════════════
        //  TAB 2 — BUSINESS PROFILE
        // ═══════════════════════════════════════════════════

        renderBusiness: function (container) {
            if (!this._isAdmin()) {
                container.innerHTML = '<div class="card"><p style="padding:40px;text-align:center;color:var(--text-secondary);">You do not have permission to access Business Settings.</p></div>';
                return;
            }
            var b = this.business;
            var self = this;

            var iconOptionsHtml = ICON_OPTIONS.map(function (opt) {
                return '<option value="' + opt.value + '"' + (b.logoIcon === opt.value ? ' selected' : '') + '>' + opt.label + '</option>';
            }).join('');

            container.innerHTML =
                '<div class="page-header">' +
                '  <div><h2>Business Profile</h2>' +
                '    <div class="breadcrumb">' +
                '      <a href="#" data-nav="dashboard">Home</a><span>/</span>' +
                '      <span>Settings</span><span>/</span><span>Business Profile</span>' +
                '    </div>' +
                '  </div>' +
                '</div>' +

                '<div class="card st-form-card">' +
                '  <div class="st-business-preview">' +
                '    <div class="st-brand-preview">' +
                '      <i class="' + self._escapeHtml(b.logoIcon) + '" id="st-icon-preview"></i>' +
                '      <div>' +
                '        <h2 id="st-name-preview">' + self._escapeHtml(b.name) + '</h2>' +
                '        <p id="st-tagline-preview">' + self._escapeHtml(b.tagline) + '</p>' +
                '      </div>' +
                '    </div>' +
                '  </div>' +

                '  <h3 class="st-section-title"><i class="fas fa-building"></i> Business Information</h3>' +
                '  <form id="st-business-form" class="st-form">' +
                '    <div class="st-form-row">' +
                '      <div class="form-group">' +
                '        <label for="st-biz-name">Business Name <span class="required">*</span></label>' +
                '        <input type="text" id="st-biz-name" value="' + self._escapeHtml(b.name) + '" required placeholder="Your Pharmacy Name">' +
                '        <small class="st-help-text">This name appears across all pages, receipts, and invoices</small>' +
                '      </div>' +
                '      <div class="form-group">' +
                '        <label for="st-biz-tagline">Tagline</label>' +
                '        <input type="text" id="st-biz-tagline" value="' + self._escapeHtml(b.tagline) + '" placeholder="e.g., Pharmacy Management System">' +
                '      </div>' +
                '    </div>' +
                '    <div class="st-form-row">' +
                '      <div class="form-group">' +
                '        <label for="st-biz-address">Address</label>' +
                '        <input type="text" id="st-biz-address" value="' + self._escapeHtml(b.address) + '" placeholder="Street, City, Country">' +
                '      </div>' +
                '      <div class="form-group">' +
                '        <label for="st-biz-phone">Phone</label>' +
                '        <input type="tel" id="st-biz-phone" value="' + self._escapeHtml(b.phone) + '" placeholder="+254 XXX XXX XXX">' +
                '      </div>' +
                '    </div>' +
                '    <div class="st-form-row">' +
                '      <div class="form-group">' +
                '        <label for="st-biz-email">Email</label>' +
                '        <input type="email" id="st-biz-email" value="' + self._escapeHtml(b.email) + '" placeholder="info@yourpharmacy.com">' +
                '      </div>' +
                '      <div class="form-group">' +
                '        <label for="st-biz-license">License Number</label>' +
                '        <input type="text" id="st-biz-license" value="' + self._escapeHtml(b.licenseNumber) + '" placeholder="PPB/XXXX">' +
                '      </div>' +
                '    </div>' +
                '    <div class="st-form-row">' +
                '      <div class="form-group">' +
                '        <label for="st-biz-icon">Logo Icon</label>' +
                '        <div class="st-icon-select-wrapper">' +
                '          <i class="' + self._escapeHtml(b.logoIcon) + '" id="st-icon-select-preview"></i>' +
                '          <select id="st-biz-icon">' + iconOptionsHtml + '</select>' +
                '        </div>' +
                '      </div>' +
                '      <div class="form-group"></div>' +
                '    </div>' +
                '    <div class="st-form-actions">' +
                '      <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save Business Info</button>' +
                '    </div>' +
                '  </form>' +
                '</div>' +

                '<div class="card st-form-card" style="margin-top:20px;">' +
                '  <h3 class="st-section-title"><i class="fas fa-image"></i> Company Logo</h3>' +
                '  <p class="st-section-desc">Upload your company logo. It will appear on receipts, invoices, and the sidebar.</p>' +
                '  <div class="st-avatar-section" style="padding:20px;">' +
                '    <div class="st-company-logo-display" id="st-company-logo-display" style="width:120px;height:120px;border-radius:12px;background:var(--bg-secondary,#f1f5f9);display:flex;align-items:center;justify-content:center;overflow:hidden;border:2px dashed var(--border-color,#e2e8f0);margin:0 auto 16px;">' +
                (b.companyLogoUrl
                    ? '<img src="' + self._escapeHtml(b.companyLogoUrl) + '" alt="Company Logo" style="width:100%;height:100%;object-fit:contain;">'
                    : '<i class="' + self._escapeHtml(b.logoIcon) + '" style="font-size:48px;color:var(--text-secondary,#94a3b8);"></i>') +
                '    </div>' +
                '    <div class="st-photo-upload">' +
                '      <label for="st-company-logo-input" class="st-photo-btn" style="cursor:pointer;"><i class="fas fa-cloud-upload-alt"></i> Upload Logo</label>' +
                '      <input type="file" id="st-company-logo-input" accept="image/png,image/jpeg,image/webp" style="display:none;">' +
                '      <div class="st-photo-status" id="st-company-logo-status"></div>' +
                (b.companyLogoUrl ? '      <button class="st-photo-remove" id="st-company-logo-remove"><i class="fas fa-trash-alt"></i> Remove Logo</button>' : '') +
                '    </div>' +
                '    <small style="color:var(--text-secondary,#94a3b8);margin-top:8px;display:block;text-align:center;">PNG, JPEG, or WebP — Max 2MB</small>' +
                '  </div>' +
                '</div>';

            self._bindBreadcrumb(container);
            self._bindBusinessForm(container);
            self._bindCompanyLogoUpload(container);

            // Live preview
            var nameInput = document.getElementById('st-biz-name');
            var taglineInput = document.getElementById('st-biz-tagline');
            var iconSelect = document.getElementById('st-biz-icon');

            if (nameInput) nameInput.addEventListener('input', function () {
                var el = document.getElementById('st-name-preview');
                if (el) el.textContent = nameInput.value || 'Your Business';
            });
            if (taglineInput) taglineInput.addEventListener('input', function () {
                var el = document.getElementById('st-tagline-preview');
                if (el) el.textContent = taglineInput.value || '';
            });
            if (iconSelect) iconSelect.addEventListener('change', function () {
                var p1 = document.getElementById('st-icon-preview');
                var p2 = document.getElementById('st-icon-select-preview');
                if (p1) p1.className = iconSelect.value;
                if (p2) p2.className = iconSelect.value;
            });
        },

        _bindBusinessForm: function (container) {
            var form = container.querySelector('#st-business-form');
            if (!form) return;
            var self = this;

            form.addEventListener('submit', async function (e) {
                e.preventDefault();
                var btn = form.querySelector('button[type="submit"]');
                btn.disabled = true;
                btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Saving...';

                try {
                    var businessId = PharmaFlow.Auth && PharmaFlow.Auth.getBusinessId ? PharmaFlow.Auth.getBusinessId() : null;
                    if (!businessId) throw new Error('No business ID found');

                    var name = document.getElementById('st-biz-name').value.trim();
                    if (!name) throw new Error('Business name is required');

                    var updates = {
                        name: name,
                        tagline: document.getElementById('st-biz-tagline').value.trim(),
                        address: document.getElementById('st-biz-address').value.trim(),
                        phone: document.getElementById('st-biz-phone').value.trim(),
                        email: document.getElementById('st-biz-email').value.trim(),
                        licenseNumber: document.getElementById('st-biz-license').value.trim(),
                        logoIcon: document.getElementById('st-biz-icon').value,
                        updatedAt: new Date().toISOString()
                    };

                    await window.db.collection('businesses').doc(businessId).update(updates);

                    if (PharmaFlow.ActivityLog) {
                        PharmaFlow.ActivityLog.log({
                            title: 'Business Profile Updated',
                            description: 'Business name: ' + name,
                            category: 'System',
                            status: 'COMPLETED'
                        });
                    }

                    self._showToast('Business profile updated — branding applied everywhere', 'success');
                } catch (err) {
                    console.error('Business update failed:', err);
                    self._showToast(err.message || 'Failed to update business profile', 'error');
                } finally {
                    btn.disabled = false;
                    btn.innerHTML = '<i class="fas fa-save"></i> Save Business Info';
                }
            });
        },

        _bindCompanyLogoUpload: function (container) {
            var self = this;
            var fileInput = document.getElementById('st-company-logo-input');
            var statusEl = document.getElementById('st-company-logo-status');
            var removeBtn = document.getElementById('st-company-logo-remove');

            if (fileInput) {
                fileInput.addEventListener('change', async function () {
                    var file = fileInput.files[0];
                    if (!file) return;

                    if (!file.type.match(/^image\/(png|jpeg|webp)$/)) {
                        self._showToast('Please select a PNG, JPEG, or WebP image', 'error');
                        fileInput.value = '';
                        return;
                    }
                    if (file.size > 2 * 1024 * 1024) {
                        self._showToast('Image must be less than 2MB', 'error');
                        fileInput.value = '';
                        return;
                    }

                    var businessId = PharmaFlow.Auth && PharmaFlow.Auth.getBusinessId ? PharmaFlow.Auth.getBusinessId() : null;
                    if (!businessId) { self._showToast('No business assigned', 'error'); return; }

                    if (statusEl) statusEl.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Uploading...';

                    try {
                        var ext = file.name.split('.').pop().toLowerCase();
                        var ref = window.storage.ref('businesses/' + businessId + '/company_logo/logo.' + ext);
                        var snapshot = await ref.put(file);
                        var downloadURL = await snapshot.ref.getDownloadURL();

                        await window.db.collection('businesses').doc(businessId).update({
                            companyLogoUrl: downloadURL,
                            updatedAt: new Date().toISOString()
                        });

                        Settings.business.companyLogoUrl = downloadURL;

                        var displayEl = document.getElementById('st-company-logo-display');
                        if (displayEl) displayEl.innerHTML = '<img src="' + self._escapeHtml(downloadURL) + '" alt="Company Logo" style="width:100%;height:100%;object-fit:contain;">';

                        if (statusEl) statusEl.innerHTML = '<i class="fas fa-check" style="color:#16a34a;"></i> Uploaded!';
                        setTimeout(function () { if (statusEl) statusEl.innerHTML = ''; }, 3000);

                        if (!document.getElementById('st-company-logo-remove')) {
                            var uploadDiv = container.querySelector('.st-photo-upload');
                            if (uploadDiv) {
                                var btn = document.createElement('button');
                                btn.className = 'st-photo-remove';
                                btn.id = 'st-company-logo-remove';
                                btn.innerHTML = '<i class="fas fa-trash-alt"></i> Remove Logo';
                                uploadDiv.appendChild(btn);
                                btn.addEventListener('click', function () { self._removeCompanyLogo(container); });
                            }
                        }

                        if (PharmaFlow.ActivityLog) {
                            PharmaFlow.ActivityLog.log({
                                title: 'Company Logo Updated',
                                description: 'Company logo uploaded to Storage',
                                category: 'System',
                                status: 'COMPLETED'
                            });
                        }

                        self._showToast('Company logo updated', 'success');
                    } catch (err) {
                        console.error('Company logo upload failed:', err);
                        if (statusEl) statusEl.innerHTML = '';
                        self._showToast('Failed to upload logo: ' + (err.message || 'Unknown error'), 'error');
                    }

                    fileInput.value = '';
                });
            }

            if (removeBtn) {
                removeBtn.addEventListener('click', function () { self._removeCompanyLogo(container); });
            }
        },

        _removeCompanyLogo: async function (container) {
            var self = this;
            var businessId = PharmaFlow.Auth && PharmaFlow.Auth.getBusinessId ? PharmaFlow.Auth.getBusinessId() : null;
            if (!businessId) return;

            try {
                await window.db.collection('businesses').doc(businessId).update({
                    companyLogoUrl: firebase.firestore.FieldValue.delete(),
                    updatedAt: new Date().toISOString()
                });

                try {
                    var extensions = ['png', 'jpeg', 'jpg', 'webp'];
                    for (var i = 0; i < extensions.length; i++) {
                        try {
                            await window.storage.ref('businesses/' + businessId + '/company_logo/logo.' + extensions[i]).delete();
                        } catch (e) { /* file may not exist with this extension */ }
                    }
                } catch (e) { /* ignore storage errors */ }

                Settings.business.companyLogoUrl = '';

                var displayEl = document.getElementById('st-company-logo-display');
                if (displayEl) displayEl.innerHTML = '<i class="' + self._escapeHtml(Settings.business.logoIcon) + '" style="font-size:48px;color:var(--text-secondary,#94a3b8);"></i>';

                var removeBtn = document.getElementById('st-company-logo-remove');
                if (removeBtn) removeBtn.remove();

                self._showToast('Company logo removed', 'success');
            } catch (err) {
                console.error('Remove company logo failed:', err);
                self._showToast('Failed to remove logo', 'error');
            }
        },


        // ═══════════════════════════════════════════════════
        //  TAB 3 — RECEIPTS & INVOICES
        // ═══════════════════════════════════════════════════

        renderReceipts: function (container) {
            if (!this._isAdmin()) {
                container.innerHTML = '<div class="card"><p style="padding:40px;text-align:center;color:var(--text-secondary);">You do not have permission to access these settings.</p></div>';
                return;
            }
            var b = this.business;
            var self = this;

            container.innerHTML =
                '<div class="page-header">' +
                '  <div><h2>Receipts & Invoices</h2>' +
                '    <div class="breadcrumb">' +
                '      <a href="#" data-nav="dashboard">Home</a><span>/</span>' +
                '      <span>Settings</span><span>/</span><span>Receipts & Invoices</span>' +
                '    </div>' +
                '  </div>' +
                '</div>' +

                '<div class="st-receipts-grid">' +

                '  <div class="card st-form-card">' +
                '    <h3 class="st-section-title"><i class="fas fa-receipt"></i> Receipt Settings</h3>' +
                '    <p class="st-section-desc">Customize how POS receipts appear when printed</p>' +
                '    <form id="st-receipt-form" class="st-form">' +
                '      <div class="form-group">' +
                '        <label for="st-receipt-footer">Receipt Footer Message</label>' +
                '        <input type="text" id="st-receipt-footer" value="' + self._escapeHtml(b.receiptFooter) + '" placeholder="Thank you for your purchase!">' +
                '        <small class="st-help-text">Appears at the bottom of every receipt</small>' +
                '      </div>' +
                '      <div class="st-preview-box">' +
                '        <h4><i class="fas fa-eye"></i> Receipt Preview</h4>' +
                '        <div class="st-receipt-preview">' +
                '          <div class="st-rp-header">' +
                '            <i class="' + self._escapeHtml(b.logoIcon) + '"></i>' +
                '            <strong id="st-rp-name">' + self._escapeHtml(b.name) + '</strong>' +
                '            <small>Sales Receipt</small>' +
                '          </div>' +
                '          <div class="st-rp-divider"></div>' +
                '          <div class="st-rp-line"><span>Item Example</span><span>KSH 500</span></div>' +
                '          <div class="st-rp-line"><span>Item Two</span><span>KSH 300</span></div>' +
                '          <div class="st-rp-line st-rp-bold"><span>TOTAL</span><span>KSH 800</span></div>' +
                '          <div class="st-rp-divider"></div>' +
                '          <div class="st-rp-footer" id="st-rp-footer">' + self._escapeHtml(b.receiptFooter) + '</div>' +
                '        </div>' +
                '      </div>' +
                '      <div class="st-form-actions">' +
                '        <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save Receipt Settings</button>' +
                '      </div>' +
                '    </form>' +
                '  </div>' +

                '  <div class="card st-form-card">' +
                '    <h3 class="st-section-title"><i class="fas fa-file-invoice"></i> Invoice Settings</h3>' +
                '    <p class="st-section-desc">Customize wholesale invoice appearance</p>' +
                '    <form id="st-invoice-form" class="st-form">' +
                '      <div class="form-group">' +
                '        <label for="st-invoice-footer">Invoice Thank You Message</label>' +
                '        <input type="text" id="st-invoice-footer" value="' + self._escapeHtml(b.invoiceFooter) + '" placeholder="Thank you for your business!">' +
                '      </div>' +
                '      <div class="form-group">' +
                '        <label for="st-invoice-generated">Invoice Generated Text</label>' +
                '        <input type="text" id="st-invoice-generated" value="' + self._escapeHtml(b.invoiceGenerated || 'This invoice was generated by {name} {tagline}') + '" placeholder="Use {name} and {tagline} as placeholders">' +
                '        <small class="st-help-text">Use {name} for business name and {tagline} for tagline</small>' +
                '      </div>' +
                '      <div class="st-preview-box">' +
                '        <h4><i class="fas fa-eye"></i> Invoice Header Preview</h4>' +
                '        <div class="st-invoice-preview">' +
                '          <div class="st-ip-header">' +
                '            <div class="st-ip-brand">' +
                '              <i class="' + self._escapeHtml(b.logoIcon) + '"></i>' +
                '              <strong id="st-ip-name">' + self._escapeHtml(b.name) + '</strong>' +
                '            </div>' +
                '            <small id="st-ip-tagline">' + self._escapeHtml(b.tagline) + '</small>' +
                '          </div>' +
                '          <div class="st-ip-title">INVOICE</div>' +
                '        </div>' +
                '      </div>' +
                '      <div class="st-form-actions">' +
                '        <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save Invoice Settings</button>' +
                '      </div>' +
                '    </form>' +
                '  </div>' +

                '</div>';

            self._bindBreadcrumb(container);
            self._bindReceiptForm(container);
            self._bindInvoiceForm(container);

            // Live receipt footer preview
            var footerInput = document.getElementById('st-receipt-footer');
            if (footerInput) footerInput.addEventListener('input', function () {
                var el = document.getElementById('st-rp-footer');
                if (el) el.textContent = footerInput.value;
            });
        },

        _bindReceiptForm: function (container) {
            var form = container.querySelector('#st-receipt-form');
            if (!form) return;
            var self = this;

            form.addEventListener('submit', async function (e) {
                e.preventDefault();
                var btn = form.querySelector('button[type="submit"]');
                btn.disabled = true;
                btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Saving...';

                try {
                    var businessId = PharmaFlow.Auth && PharmaFlow.Auth.getBusinessId ? PharmaFlow.Auth.getBusinessId() : null;
                    if (!businessId) throw new Error('No business ID');

                    await window.db.collection('businesses').doc(businessId).update({
                        receiptFooter: document.getElementById('st-receipt-footer').value.trim(),
                        updatedAt: new Date().toISOString()
                    });

                    self._showToast('Receipt settings saved', 'success');
                } catch (err) {
                    self._showToast(err.message || 'Failed to save', 'error');
                } finally {
                    btn.disabled = false;
                    btn.innerHTML = '<i class="fas fa-save"></i> Save Receipt Settings';
                }
            });
        },

        _bindInvoiceForm: function (container) {
            var form = container.querySelector('#st-invoice-form');
            if (!form) return;
            var self = this;

            form.addEventListener('submit', async function (e) {
                e.preventDefault();
                var btn = form.querySelector('button[type="submit"]');
                btn.disabled = true;
                btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Saving...';

                try {
                    var businessId = PharmaFlow.Auth && PharmaFlow.Auth.getBusinessId ? PharmaFlow.Auth.getBusinessId() : null;
                    if (!businessId) throw new Error('No business ID');

                    await window.db.collection('businesses').doc(businessId).update({
                        invoiceFooter: document.getElementById('st-invoice-footer').value.trim(),
                        invoiceGenerated: document.getElementById('st-invoice-generated').value.trim(),
                        updatedAt: new Date().toISOString()
                    });

                    self._showToast('Invoice settings saved', 'success');
                } catch (err) {
                    self._showToast(err.message || 'Failed to save', 'error');
                } finally {
                    btn.disabled = false;
                    btn.innerHTML = '<i class="fas fa-save"></i> Save Invoice Settings';
                }
            });
        },


        // ═══════════════════════════════════════════════════
        //  TAB 4 — NOTIFICATIONS
        // ═══════════════════════════════════════════════════

        renderNotifications: function (container) {
            var b = this.business;
            var self = this;
            var isAdmin = self._isAdmin();
            var messaging = self.getMessagingIntegrations ? self.getMessagingIntegrations() : {};

            container.innerHTML =
                '<div class="page-header">' +
                '  <div><h2>Notification Settings</h2>' +
                '    <div class="breadcrumb">' +
                '      <a href="#" data-nav="dashboard">Home</a><span>/</span>' +
                '      <span>Settings</span><span>/</span><span>Notifications</span>' +
                '    </div>' +
                '  </div>' +
                '</div>' +

                '<div class="card st-form-card">' +
                '  <h3 class="st-section-title"><i class="fas fa-bell"></i> System Notifications</h3>' +
                '  <p class="st-section-desc">Configure which notifications the system generates' + (isAdmin ? '' : ' (view only — admin can change)') + '</p>' +
                '  <form id="st-notif-form" class="st-form">' +
                '    <div class="st-toggle-group">' +

                '      <div class="st-toggle-item">' +
                '        <div class="st-toggle-info">' +
                '          <strong>Low Stock Alerts</strong>' +
                '          <p>Get notified when inventory items fall below threshold</p>' +
                '        </div>' +
                '        <label class="st-switch">' +
                '          <input type="checkbox" id="st-notif-low-stock"' + (b.notifyLowStock ? ' checked' : '') + (isAdmin ? '' : ' disabled') + '>' +
                '          <span class="st-slider"></span>' +
                '        </label>' +
                '      </div>' +

                '      <div class="st-toggle-item">' +
                '        <div class="st-toggle-info">' +
                '          <strong>Expiry Alerts</strong>' +
                '          <p>Get notified when products are about to expire</p>' +
                '        </div>' +
                '        <label class="st-switch">' +
                '          <input type="checkbox" id="st-notif-expiry"' + (b.notifyExpiry ? ' checked' : '') + (isAdmin ? '' : ' disabled') + '>' +
                '          <span class="st-slider"></span>' +
                '        </label>' +
                '      </div>' +

                '      <div class="st-toggle-item">' +
                '        <div class="st-toggle-info">' +
                '          <strong>New Order Alerts</strong>' +
                '          <p>Get notified when new wholesale orders are placed</p>' +
                '        </div>' +
                '        <label class="st-switch">' +
                '          <input type="checkbox" id="st-notif-orders"' + (b.notifyNewOrders ? ' checked' : '') + (isAdmin ? '' : ' disabled') + '>' +
                '          <span class="st-slider"></span>' +
                '        </label>' +
                '      </div>' +

                '    </div>' +

                (isAdmin ?
                    '    <div class="st-messaging-summary">' +
                    '      <div>' +
                    '        <strong>Messaging provider setup</strong>' +
                    '        <p>Open the setup modal to configure Africa\'s Talking, EmailJS, and WhatsApp credentials.</p>' +
                    '      </div>' +
                    '      <button type="button" class="btn btn-outline" id="st-open-messaging-modal"><i class="fas fa-comments"></i> Messaging Setup</button>' +
                    '    </div>' : '') +

                (isAdmin ?
                    '    <hr class="st-divider">' +
                    '    <h3 class="st-section-title"><i class="fas fa-sliders-h"></i> Alert Thresholds</h3>' +
                    '    <div class="st-form-row">' +
                    '      <div class="form-group">' +
                    '        <label for="st-low-stock-threshold">Low Stock Threshold</label>' +
                    '        <input type="number" id="st-low-stock-threshold" value="' + (b.lowStockThreshold || 10) + '" min="1" max="1000">' +
                    '        <small class="st-help-text">Alert when quantity falls below this number</small>' +
                    '      </div>' +
                    '      <div class="form-group">' +
                    '        <label for="st-expiry-warning">Expiry Warning (Days)</label>' +
                    '        <input type="number" id="st-expiry-warning" value="' + (b.expiryWarningDays || 30) + '" min="1" max="365">' +
                    '        <small class="st-help-text">Alert this many days before expiry</small>' +
                    '      </div>' +
                    '    </div>' +
                    '    <div class="st-form-actions">' +
                    '      <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save Notification Settings</button>' +
                    '    </div>'
                    : '') +

                '  </form>' +
                '</div>';

            if (isAdmin) {
                var modal = document.createElement('div');
                modal.className = 'pc-modal-overlay st-messaging-modal hidden';
                modal.id = 'st-messaging-modal';
                modal.innerHTML =
                    '<div class="pc-modal-card pc-message-modal-card st-messaging-modal-card">' +
                    '  <div class="pc-modal-header">' +
                    '    <h3><i class="fas fa-comments"></i> Messaging Setup</h3>' +
                    '    <button class="slide-panel-close" id="st-messaging-close"><i class="fas fa-times"></i></button>' +
                    '  </div>' +
                    '  <div class="pc-modal-meta">' +
                    '    <span><strong>Provider:</strong> Africa\'s Talking for SMS, EmailJS for email, CallMeBot for WhatsApp</span>' +
                    '  </div>' +
                    '  <div class="pc-modal-body">' +
                    '    <div class="st-form-row">' +
                    '      <div class="form-group">' +
                    '        <label for="st-msg-provider">Messaging Mode</label>' +
                    '        <select id="st-msg-provider">' +
                    '          <option value="mixed"' + (messaging.provider === 'mixed' ? ' selected' : '') + '>Mixed (recommended)</option>' +
                    '          <option value="africastalking"' + (messaging.provider === 'africastalking' ? ' selected' : '') + '>Africa\'s Talking SMS</option>' +
                    '        </select>' +
                    '        <small class="st-help-text">Use Mixed for SMS + email + WhatsApp, or Africa\'s Talking for SMS-only.</small>' +
                    '      </div>' +
                    '      <div class="form-group">' +
                    '        <label for="st-at-sender">Africa\'s Talking Sender ID</label>' +
                    '        <input type="text" id="st-at-sender" value="' + self._escapeHtml(messaging.africaTalkingSenderId || '') + '" placeholder="Your sender ID">' +
                    '      </div>' +
                    '    </div>' +
                    '    <div class="st-form-row">' +
                    '      <div class="form-group">' +
                    '        <label for="st-at-user">Africa\'s Talking Username</label>' +
                    '        <input type="text" id="st-at-user" value="' + self._escapeHtml(messaging.africaTalkingUsername || '') + '" placeholder="sandbox or live username">' +
                    '      </div>' +
                    '      <div class="form-group">' +
                    '        <label for="st-at-key">Africa\'s Talking API Key</label>' +
                    '        <input type="password" id="st-at-key" value="' + self._escapeHtml(messaging.africaTalkingApiKey || '') + '" placeholder="API key">' +
                    '      </div>' +
                    '    </div>' +
                    '    <hr class="st-divider">' +
                    '    <p class="st-section-desc">Email and WhatsApp still use separate free services. Fill only what you need.</p>' +
                    '    <div class="st-form-row">' +
                    '      <div class="form-group">' +
                    '        <label for="st-emailjs-service-modal">EmailJS Service ID</label>' +
                    '        <input type="text" id="st-emailjs-service-modal" value="' + self._escapeHtml(messaging.emailJsServiceId || '') + '" placeholder="service_xxxxx">' +
                    '      </div>' +
                    '      <div class="form-group">' +
                    '        <label for="st-emailjs-template-modal">EmailJS Template ID</label>' +
                    '        <input type="text" id="st-emailjs-template-modal" value="' + self._escapeHtml(messaging.emailJsTemplateId || '') + '" placeholder="template_xxxxx">' +
                    '      </div>' +
                    '    </div>' +
                    '    <div class="st-form-row">' +
                    '      <div class="form-group">' +
                    '        <label for="st-emailjs-key-modal">EmailJS Public Key</label>' +
                    '        <input type="text" id="st-emailjs-key-modal" value="' + self._escapeHtml(messaging.emailJsPublicKey || '') + '" placeholder="public key">' +
                    '      </div>' +
                    '      <div class="form-group">' +
                    '        <label for="st-wa-phone-modal">WhatsApp Phone</label>' +
                    '        <input type="text" id="st-wa-phone-modal" value="' + self._escapeHtml(messaging.whatsappCallMeBotPhone || '') + '" placeholder="2547xxxxxxxx">' +
                    '      </div>' +
                    '    </div>' +
                    '    <div class="st-form-row">' +
                    '      <div class="form-group">' +
                    '        <label for="st-wa-key-modal">WhatsApp API Key</label>' +
                    '        <input type="text" id="st-wa-key-modal" value="' + self._escapeHtml(messaging.whatsappCallMeBotApiKey || '') + '" placeholder="WhatsApp API key">' +
                    '      </div>' +
                    '      <div class="form-group"></div>' +
                    '    </div>' +
                    '    <div class="pc-msg-actions">' +
                    '      <button class="btn btn-outline" id="st-messaging-cancel" type="button"><i class="fas fa-times"></i> Cancel</button>' +
                    '      <button class="btn btn-primary" id="st-messaging-save" type="button"><i class="fas fa-save"></i> Save Messaging</button>' +
                    '    </div>' +
                    '  </div>' +
                    '</div>';
                document.body.appendChild(modal);
            }

            self._bindBreadcrumb(container);
            self._bindNotifForm(container);
            if (isAdmin) self._bindMessagingModal(container);
        },

        _bindMessagingModal: function () {
            var modal = document.getElementById('st-messaging-modal');
            if (!modal) return;
            var openBtn = document.getElementById('st-open-messaging-modal');
            var close = function () { modal.classList.add('hidden'); };

            if (openBtn) openBtn.addEventListener('click', function () { modal.classList.remove('hidden'); });
            document.getElementById('st-messaging-close')?.addEventListener('click', close);
            document.getElementById('st-messaging-cancel')?.addEventListener('click', close);
            modal.addEventListener('click', function (e) { if (e.target === modal) close(); });

            document.getElementById('st-messaging-save')?.addEventListener('click', async function () {
                var btn = document.getElementById('st-messaging-save');
                if (!btn) return;
                btn.disabled = true;
                btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Saving...';

                try {
                    var businessId = PharmaFlow.Auth && PharmaFlow.Auth.getBusinessId ? PharmaFlow.Auth.getBusinessId() : null;
                    if (!businessId) throw new Error('No business ID');

                    await window.db.collection('businesses').doc(businessId).update({
                        messagingProvider: document.getElementById('st-msg-provider').value,
                        africaTalkingUsername: document.getElementById('st-at-user').value.trim(),
                        africaTalkingApiKey: document.getElementById('st-at-key').value.trim(),
                        africaTalkingSenderId: document.getElementById('st-at-sender').value.trim(),
                        emailJsServiceId: document.getElementById('st-emailjs-service-modal').value.trim(),
                        emailJsTemplateId: document.getElementById('st-emailjs-template-modal').value.trim(),
                        emailJsPublicKey: document.getElementById('st-emailjs-key-modal').value.trim(),
                        whatsappCallMeBotPhone: document.getElementById('st-wa-phone-modal').value.trim(),
                        whatsappCallMeBotApiKey: document.getElementById('st-wa-key-modal').value.trim(),
                        updatedAt: new Date().toISOString()
                    });

                    if (PharmaFlow.Settings) {
                        PharmaFlow.Settings.business.messagingProvider = document.getElementById('st-msg-provider').value;
                        PharmaFlow.Settings.business.africaTalkingUsername = document.getElementById('st-at-user').value.trim();
                        PharmaFlow.Settings.business.africaTalkingApiKey = document.getElementById('st-at-key').value.trim();
                        PharmaFlow.Settings.business.africaTalkingSenderId = document.getElementById('st-at-sender').value.trim();
                        PharmaFlow.Settings.business.emailJsServiceId = document.getElementById('st-emailjs-service-modal').value.trim();
                        PharmaFlow.Settings.business.emailJsTemplateId = document.getElementById('st-emailjs-template-modal').value.trim();
                        PharmaFlow.Settings.business.emailJsPublicKey = document.getElementById('st-emailjs-key-modal').value.trim();
                        PharmaFlow.Settings.business.whatsappCallMeBotPhone = document.getElementById('st-wa-phone-modal').value.trim();
                        PharmaFlow.Settings.business.whatsappCallMeBotApiKey = document.getElementById('st-wa-key-modal').value.trim();
                    }

                    if (PharmaFlow.Settings && PharmaFlow.Settings.persistBrandToLocal) PharmaFlow.Settings.persistBrandToLocal();
                    document.getElementById('st-messaging-modal')?.classList.add('hidden');
                    if (PharmaFlow.Settings && PharmaFlow.Settings._showToast) PharmaFlow.Settings._showToast('Messaging settings saved', 'success');
                } catch (err) {
                    if (PharmaFlow.Settings && PharmaFlow.Settings._showToast) PharmaFlow.Settings._showToast(err.message || 'Failed to save messaging settings', 'error');
                } finally {
                    btn.disabled = false;
                    btn.innerHTML = '<i class="fas fa-save"></i> Save Messaging';
                }
            });
        },

        _bindNotifForm: function (container) {
            var form = container.querySelector('#st-notif-form');
            if (!form || !this._isAdmin()) return;
            var self = this;

            form.addEventListener('submit', async function (e) {
                e.preventDefault();
                var btn = form.querySelector('button[type="submit"]');
                btn.disabled = true;
                btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Saving...';

                try {
                    var businessId = PharmaFlow.Auth && PharmaFlow.Auth.getBusinessId ? PharmaFlow.Auth.getBusinessId() : null;
                    if (!businessId) throw new Error('No business ID');

                    await window.db.collection('businesses').doc(businessId).update({
                        notifyLowStock: document.getElementById('st-notif-low-stock').checked,
                        notifyExpiry: document.getElementById('st-notif-expiry').checked,
                        notifyNewOrders: document.getElementById('st-notif-orders').checked,
                        lowStockThreshold: parseInt(document.getElementById('st-low-stock-threshold').value) || 10,
                        expiryWarningDays: parseInt(document.getElementById('st-expiry-warning').value) || 30,
                        updatedAt: new Date().toISOString()
                    });

                    self._showToast('Notification settings saved', 'success');
                } catch (err) {
                    self._showToast(err.message || 'Failed to save', 'error');
                } finally {
                    btn.disabled = false;
                    btn.innerHTML = '<i class="fas fa-save"></i> Save Notification Settings';
                }
            });
        },


        // ═══════════════════════════════════════════════════
        //  TAB 5 — SYSTEM SETTINGS
        // ═══════════════════════════════════════════════════

        renderSystem: function (container) {
            if (!this._isAdmin()) {
                container.innerHTML = '<div class="card"><p style="padding:40px;text-align:center;color:var(--text-secondary);">You do not have permission to access System Settings.</p></div>';
                return;
            }
            var b = this.business;
            var self = this;

            var currHtml = CURRENCIES.map(function (c) { return '<option value="' + c.value + '"' + (b.currency === c.value ? ' selected' : '') + '>' + c.label + '</option>'; }).join('');
            var localeHtml = LOCALES.map(function (l) { return '<option value="' + l.value + '"' + (b.locale === l.value ? ' selected' : '') + '>' + l.label + '</option>'; }).join('');
            var dateHtml = DATE_FORMATS.map(function (d) { return '<option value="' + d.value + '"' + (b.dateFormat === d.value ? ' selected' : '') + '>' + d.label + '</option>'; }).join('');
            var tzHtml = TIMEZONES.map(function (t) { return '<option value="' + t.value + '"' + (b.timezone === t.value ? ' selected' : '') + '>' + t.label + '</option>'; }).join('');

            var bizId = PharmaFlow.Auth && PharmaFlow.Auth.getBusinessId ? PharmaFlow.Auth.getBusinessId() : 'N/A';

            container.innerHTML =
                '<div class="page-header">' +
                '  <div><h2>System Settings</h2>' +
                '    <div class="breadcrumb">' +
                '      <a href="#" data-nav="dashboard">Home</a><span>/</span>' +
                '      <span>Settings</span><span>/</span><span>System</span>' +
                '    </div>' +
                '  </div>' +
                '</div>' +

                '<div class="card st-form-card">' +
                '  <h3 class="st-section-title"><i class="fas fa-globe"></i> Regional Settings</h3>' +
                '  <form id="st-system-form" class="st-form">' +
                '    <div class="st-form-row">' +
                '      <div class="form-group">' +
                '        <label for="st-currency">Currency</label>' +
                '        <select id="st-currency">' + currHtml + '</select>' +
                '      </div>' +
                '      <div class="form-group">' +
                '        <label for="st-locale">Locale</label>' +
                '        <select id="st-locale">' + localeHtml + '</select>' +
                '      </div>' +
                '    </div>' +
                '    <div class="st-form-row">' +
                '      <div class="form-group">' +
                '        <label for="st-date-format">Date Format</label>' +
                '        <select id="st-date-format">' + dateHtml + '</select>' +
                '      </div>' +
                '      <div class="form-group">' +
                '        <label for="st-timezone">Timezone</label>' +
                '        <select id="st-timezone">' + tzHtml + '</select>' +
                '      </div>' +
                '    </div>' +
                '    <div class="st-form-actions">' +
                '      <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save System Settings</button>' +
                '    </div>' +
                '  </form>' +
                '</div>' +

                '<div class="card st-form-card">' +
                '  <h3 class="st-section-title"><i class="fas fa-info-circle"></i> System Information</h3>' +
                '  <div class="st-info-grid">' +
                '    <div class="st-info-item">' +
                '      <span class="st-info-label">Application</span>' +
                '      <span class="st-info-value">' + self._escapeHtml(b.name) + '</span>' +
                '    </div>' +
                '    <div class="st-info-item">' +
                '      <span class="st-info-label">Version</span>' +
                '      <span class="st-info-value">1.0.0</span>' +
                '    </div>' +
                '    <div class="st-info-item">' +
                '      <span class="st-info-label">Platform</span>' +
                '      <span class="st-info-value">Firebase / Web</span>' +
                '    </div>' +
                '    <div class="st-info-item">' +
                '      <span class="st-info-label">Business ID</span>' +
                '      <span class="st-info-value st-mono">' + self._escapeHtml(bizId) + '</span>' +
                '    </div>' +
                '  </div>' +
                '</div>';

            self._bindBreadcrumb(container);
            self._bindSystemForm(container);
        },

        _bindSystemForm: function (container) {
            var form = container.querySelector('#st-system-form');
            if (!form) return;
            var self = this;

            form.addEventListener('submit', async function (e) {
                e.preventDefault();
                var btn = form.querySelector('button[type="submit"]');
                btn.disabled = true;
                btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Saving...';

                try {
                    var businessId = PharmaFlow.Auth && PharmaFlow.Auth.getBusinessId ? PharmaFlow.Auth.getBusinessId() : null;
                    if (!businessId) throw new Error('No business ID');

                    await window.db.collection('businesses').doc(businessId).update({
                        currency: document.getElementById('st-currency').value,
                        locale: document.getElementById('st-locale').value,
                        dateFormat: document.getElementById('st-date-format').value,
                        timezone: document.getElementById('st-timezone').value,
                        updatedAt: new Date().toISOString()
                    });

                    if (PharmaFlow.ActivityLog) {
                        PharmaFlow.ActivityLog.log({
                            title: 'System Settings Updated',
                            description: 'Regional and system settings were updated',
                            category: 'System',
                            status: 'COMPLETED'
                        });
                    }

                    self._showToast('System settings saved', 'success');
                } catch (err) {
                    self._showToast(err.message || 'Failed to save', 'error');
                } finally {
                    btn.disabled = false;
                    btn.innerHTML = '<i class="fas fa-save"></i> Save System Settings';
                }
            });
        },

        // ─── CLEANUP ─────────────────────────────────────

        cleanup: function () {
            // Business listener stays active for branding across the entire app
        }
    };


    // ─── APPLY CACHED BRANDING IMMEDIATELY (before auth) ──

    (function applyCachedBrand() {
        try {
            var cached = localStorage.getItem('pf_brand_name');
            var cachedIcon = localStorage.getItem('pf_brand_icon');
            var cachedTagline = localStorage.getItem('pf_brand_tagline');
            if (cached) {
                var logoText = document.querySelector('.logo-text');
                if (logoText) logoText.textContent = cached;
                var topbarTitle = document.querySelector('.topbar-title');
                if (topbarTitle) topbarTitle.textContent = cached;
                document.title = cached + ' - ' + (cachedTagline || 'Pharmacy Management System');
            }
            if (cachedIcon) {
                var logoIcon = document.querySelector('.sidebar-logo > i');
                if (logoIcon) logoIcon.className = cachedIcon;
            }
        } catch (e) { /* ignore */ }
    })();

    // Auto-init on auth-ready
    window.addEventListener('auth-ready', function () {
        Settings.init();
    });

    window.PharmaFlow.Settings = Settings;
})();
